[build]
  publish = "dist"
  command = "npm install && npx vite build"

[build.environment]
  NODE_ENV = "production"
  NODE_VERSION = "20"

[functions]
  directory = "api"
  node_bundler = "esbuild"

[functions."generate"]
  runtime = "nodejs20.x"

[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"

# Redirect all API calls to serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200